@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle

actor Utente
actor Amministratore

package "Autenticazione" {
  (Registrazione) as UC1
  (Login) as UC2
  (Logout) as UC3
}

package "Catalogo Set LEGO" {
  (Visualizza Set) as UC4
  (Elimina Set) as UC5
  (Modifica Set) as UC6
  (Aggiungi Set) as UC7
}

package "Catalogo Pezzi" {
  (Visualizza Pezzi) as UC8
  (Scegli Pezzi) as UC9
  (Acquisto Pezzi) as UC10
}

package "Contenuti e Tutorial" {
  (Immagini Invenzioni) as UC11
  (Storia LEGO) as UC12
}

UC10 ..> UC9 : <<include>> ' Per acquistare è obbligatorio scegliere i pezzi

UC7 ..> UC4 : <<include>> ' Aggiunta obbligatoria per vedere i set

UC5 ..> UC4 : <<extend>>  ' Eliminazione set è opzionale
UC6 ..> UC4 : <<extend>>  ' Modifica set è opzionale
UC7 ..> UC4 : <<extend>>  ' Aggiunta set è opzionale

Utente --> UC1
Utente --> UC2
Utente --> UC3

Utente --> UC4
Utente --> UC8
Utente --> UC9
Utente --> UC10
Utente --> UC11
Utente --> UC12

Amministratore --> UC2
Amministratore --> UC3
Amministratore --> UC4
Amministratore --> UC5
Amministratore --> UC6
Amministratore --> UC7

@enduml